---
# tasks file for db

- name: add mysql repo
  yum:
    name: http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm
    state: present
    use_backend: yum

- name: install mysql-server
  yum: name=mysql-server state=present use_backend=yum

- name: copy shop sql files
  copy: src=shop.sql dest={{ dest }}

- name: copy login sql fil
  copy: src=login.sql dest={{ dest }}

- name: enable mysql service
  service: name=mysqld enabled=yes state=started

- name: mysql ucun port  3306
  wait_for:
    host: 0.0.0.0
    port: 3306
    delay: 10
    state: drained

- name: find mysql temporary password
  shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
  register: mysql_temp_root_password
  tags: register

- name: set new root password defined in defaults
  shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ mysql_root_password }}'');" --connect-expired-password -u root -p"{{ mysql_temp_root_password.stdout }}"'

- name: restore shop database from backup
  shell: 'mysql -u root -p"{{ mysql_root_password }}" shop < /root/shop.sql'
  
  - name: create login and database + grant privileges
  shell: 'mysql -u root -p"{{ mysql_root_password }}" mysql < /root/login.sql'

- name: cleanup files
  file:
    state: absent
    path: "{{ dest }}/login.sql"

- name: clean file
  file:
    state: absent
    path: "{{ dest }}/shop.sql"
